---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk'

inputs:
  - name: pal-tracker
#  - name: version

run:
  path: bash
  args:
  - -exc
  - |
    cd pal-tracker
    pwd
    chmod u+x ./gradlew
    ./gradlew build
    cp build/libs/pal-tracker.jar ../build-output